lib/chef/provisioning/fog_driver/providers/aws.rb
Fixes #80. 
If you want to use IAM roles on the provisioner host instead of using secret key and key ID, specify the driver URL with fog:AWS:IAM:<region>.  The provisioner needs permission to create, terminate, reboot, and describe-instances.
=> Added IAM role support for provisioner hosts.

lib/chef/provisioning/fog_driver/providers/aws.rb
Here's a different approach to the problem in #79. I *think* this is what was being asked for there.
Anyhow, this change allowed me to set my own convergence_options.
=> Handle convergence_options with MergedConfig.

lib/chef/provider/fog_key_pair.rb
=> Updating for wrong method error

lib/chef/provisioning/fog_driver/driver.rb
=> Change 'location' hash to 'reference', fixes #116

README.md
- Adding some more specific information for chef-provisioning-fog
=> Adding to the README.md

README.md
Ping @jjasghar -- here's an example for you! I also ended up opening #129 and #130 during the process :)
- Add Rackspace example with single-server create and destroy.
- Add link to other repo with example-in-a-box.
=> Add a Rackspace example with code samples/links

chef-provisioning-fog.gemspec
=> Add gemspec files to allow bundler to run from the gem

CHANGELOG.md, lib/chef/provisioning/fog_driver/version.rb
- Updated Changelog to autogenerated
- Updated Version number to the bug fix
=> 0.15.1 release

CHANGELOG.md, lib/chef/provisioning/fog_driver/version.rb
- reverted the `UTC` due to Class issues.
=> 0.15.2 release

README.md
- Fog Excon Timing
- Machine provisioning Timing
- Chef-Client converge Timing
=> Add a section on how to update timing correctly.

.travis.yml
- Per customer request added the ability for travis to deploy to
rubygems.
=> Added rubygems deployment

README.md, examples/openstack/simple.rb, examples/rackspace/simple.rb
=> Updating Docs for better organization :)

CHANGELOG.md, lib/chef/provisioning/fog_driver/version.rb
@tyler-ball can you take a look? I think we're good to release a new version of this gem!
/cc @Afterglow
=> v0.16.0 prep work

README.md, examples/joyent/infrastructure.rb
Joyent Public and Private cloud documentation
=> Joyent documentation

CHANGELOG.md, chef-provisioning-fog.gemspec, lib/chef/provider/fog_key_pair.rb
-  fixes a few things including the DO/everyother cloud issue
=> Updated fog

.gitignore, Gemfile, Rakefile, spec/spec_helper.rb
- Added files to the .gitignore for validation
- Added code coverage to the Gemfile
- Added rake task for spec
- Added codecoverage to spec_helper
=> Added more to the testing frame work

.gitignore, README.md, examples/aws/simple.rb
- Added aws.rb to .gitignore
- Updated README.md to be better organized
- Added simple.rb to aws/
=> AWS documentation

examples/digitalocean/simple.rb, lib/chef/provisioning/fog_driver/driver.rb, lib/chef/provisioning/fog_driver/version.rb
- Digital Ocean doesn't have a `state` method, this is a work around to resolve it.
=> Work around for DigitalOcean

lib/chef/provisioning/fog_driver/providers/digitalocean.rb, lib/chef/provisioning/fog_driver/providers/google.rb, lib/chef/provisioning/fog_driver/providers/joyent.rb, lib/chef/provisioning/fog_driver/providers/openstack.rb, lib/chef/provisioning/fog_driver/providers/rackspace.rb, lib/chef/provisioning/fog_driver/providers/softlayer.rb
- Added DigitialOcean
- Added GCE
- Added OpenStack
- Added Rackspace
- Added Softlayer
=> Adding ohai hints to drivers

README.md, lib/chef/provisioning/fog_driver/providers/xenserver.rb
Fixes #183 and #123 
Add Xenserver provider README
I try to follow all [guidelines for contributing](https://github.com/chef/chef-provisioning/blob/master/CONTRIBUTING.md). Hope this patch can be merged into mainstream
Regards
=> Fix xenserver provider to be compatible with xenserver 6.5

README.md, examples/xenserver/simple.rb
- added new simple.rb
- reworded section
=> Added standard documentation for XenServer

lib/chef/provisioning/fog_driver/providers/aws.rb
=> User data windows

lib/chef/provisioning/fog_driver/providers/openstack.rb
=> Load all Openstack.compute_options_for from FOG_RC

.travis.yml
Signed-off-by: Julien 'Lta' BALLET <contact@lta.io>
=> Bump ruby to 2.3.2 in travis

.gitignore, CHANGELOG.md, chef-provisioning-fog.gemspec, lib/chef/provisioning/fog_driver/version.rb
releasing 0.21.0
Signed-off-by: JJ Asghar <jj@chef.io>
=> 0.21.0 release

.travis.yml, Gemfile, chef-provisioning-fog.gemspec, examples/vcair/vcloud_director_simple.rb, lib/chef/provisioning/fog_driver/driver.rb, lib/chef/provisioning/fog_driver/providers/joyent.rb, lib/chef/provisioning/fog_driver/providers/softlayer.rb, lib/chef/provisioning/fog_driver/providers/vcair.rb, lib/chef/provisioning/fog_driver/providers/xenserver.rb, lib/chef/provisioning/fog_driver/recipe_dsl.rb, lib/chef/provisioning/fog_driver/version.rb
I updated the vcair driver in the hopes of getting it working better with vCloud Director.  I tried to make it similar to [chef-provisioning-vra](https://github.com/chef-partners/chef-provisioning-vra), but I understand that it changes how the vcair driver works compared to the other fog drivers.
I've switched it from using knife configuration options to use `driver_options` and made some changes to the driver url.  If it doesn't mesh well, let me know.  I'd appreciate the feedback.
If it looks good, I can provide documentation for the changes.
=> Vcair changes

chef-provisioning-fog.gemspec
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Loosen the cheffish dependency

lib/chef/provisioning/fog_driver/driver.rb
Signed-off-by: Baurzhan Konurbayev <baurzhan_konurbayev@epam.com>
=> Fix empty SSH username in ssh_gateway parameter

.travis.yml, Gemfile, README.md, chef-provisioning-fog.gemspec
only trying to fix cheffish now
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
=> Fix for Chef-13/ChefDK2/Cheffish 5.x/13.x, removal of fog mega-gem

chef-provisioning-fog.gemspec
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
=> bump cheffish dep for 14

.travis.yml
Take out tag based deploys and slack notification.
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Update travis config for latest ruby releases

.travis.yml, Gemfile, README.md, Rakefile, chef-provisioning-fog.gemspec
Sync the readme with reality and fixup the gemspec / Rakefile / Gemfile a bit.
=> Cleanup the readme to remove google + update gemspec fields
